# Generated by Django 3.2.4 on 2023-02-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='یوزرنیم')),
                ('first_name', models.CharField(max_length=60, verbose_name='نام')),
                ('last_name', models.CharField(max_length=60, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=200, verbose_name='پسورد')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('token', models.CharField(blank=True, max_length=40, null=True, verbose_name='توکن')),
            ],
            options={
                'verbose_name': 'کاربر خاطره نگار',
                'verbose_name_plural': 'کابر های خاطره نگار',
            },
        ),
    ]
