# Generated by Django 3.2.4 on 2023-02-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('name', models.CharField(max_length=60, verbose_name='نام')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('book', 'کتاب'), ('video', 'ویدئو'), ('music', 'موزیک'), ('picture', 'عکس')], default='book', max_length=50, verbose_name='تایپ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='contentmanagement.user', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کتاب\u200cخانه',
                'verbose_name_plural': 'کتاب\u200cخانه\u200cها',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('file', models.FileField(upload_to='library/files/')),
                ('description', models.TextField()),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contentmanagement.library')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
