# Generated by Django 3.2.4 on 2023-02-24 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0006_auto_20230223_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryfile',
            options={'verbose_name': 'فایل', 'verbose_name_plural': 'فایل ها'},
        ),
        migrations.AddField(
            model_name='libraryfile',
            name='attachment_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libraryfile',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='libraries', to='contentmanagement.User', verbose_name='کاربر\u200cها'),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='libraryfile',
            unique_together={('library', 'file')},
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ساخت')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخرین زمان تغییر')),
                ('field', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='library/files/')),
                ('library_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contentmanagement.libraryfile')),
            ],
            options={
                'verbose_name': 'پیوست',
                'verbose_name_plural': 'پیوست ها',
            },
        ),
    ]
