# Generated by Django 3.2.4 on 2023-02-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0007_auto_20230224_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('library_file', 'file')},
        ),
    ]
