# Generated by Django 3.2.4 on 2023-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0008_alter_attachment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='field',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
