# Generated by Django 3.2.4 on 2023-02-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کابر ها'},
        ),
    ]
